### PR TITLE
Release v0.4.0

### PR DESCRIPTION
**Pull request by arkgil**
Publish a release with `:reporter_options` so that we can start using it in the reporters.

Let me know if I missed something in the change log, but I think that `:reporter_options` was the only API change.

### CODE REVIEW

**Comment by arkgil** [comment]
Of course, we're still testing on an old version and it won't compile.

**Comment by josevalim** [comment]
@arkgil IMO, just remove the dialyxir dependency. :)

**Comment by bryannaegele** [comment]
@josevalim are we still supporting 1.5?

**Comment by arkgil** [comment]
With 1.10, 1.6 is going to be the last version getting security patches.

**Comment by josevalim** [comment]
Yeah, we can require v1.6+ too!

**Comment by arkgil** [comment]
Eh, for some reason it didn't pick up the new CI config file. Anyway, this doesn't add any new code, and we have #58 with green checks. I'd merge this one and spin a fresh build from master just to have a confirmation.

**Comment by arkgil** [comment]
@josevalim @bryannaegele good to go from your side?

**Comment by josevalim** [comment]
Yes!

**Pull request merged**
